site_name: Root Path
theme:
  name: terminal
  palette: pink

nav:
  - Главная: 'index.md'
  - Сети: 'net/index.md'
  - Телефония: 'voip/index.md'

# ----------------------------------
#
# DEVELOP ВЕТКА
#
# 1 Python Virtual Environment
#
# sudo apt install python3-venv python3-pip -y
# python3 -m venv .venv
#
# source .venv/bin/activate
#
# pip install mkdocs mkdocs-terminal
# 
# 2 MkDocs
# 
# mkdocs --version
# mkdocs serve - запуск локального сервера
# mkdocs build - сборка в папку site
#
# 3 git add & git commit
#
# ----------------------------------
#
# MAIN ВЕТКА
# 
# git merge develop & git push
# 
# mkdocs gh-deploy
# 
# deactivate 
#